version: '3.9'
services: 
  backend:
    build: 
      context: .
    ports: 
      - '80:80'
      - '8080:8080'
    depends_on:
      database: 
        condition: service_healthy
    environment:
      - DB_HOST=database

  database:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_PASSWORD: MyP@ssw0rdI5veryH@rd
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
